# IMPROVE-SPARTAN May Prep Task Map

Purpose: turn the April 22/Ann follow-up task list into a repo-grounded work plan for the May Warren/Sina discussions.

This notebook does **not** start a new raw data analysis branch. It inventories what is already available in the repo, loads the key existing output tables, and separates:

- work that is already done or mostly done,
- work that can be polished from existing outputs,
- work blocked by external metadata or direct expert follow-up.

Important caveat: FED exposes laser reflectance/transmittance ratio fields, but not the raw Warren Figure 2 HIPS sphere/plate signals, blanks, lot IDs, blank-line OLS coefficients, or analysis batch metadata. Treat FED R/T plots as diagnostic analogs, not a reproduction of Warren Figure 2.

In [1]:
from __future__ import annotations

from pathlib import Path
import sys

import pandas as pd

ROOT = Path('../..').resolve()
FTIR = ROOT / 'research' / 'ftir_hips_chem'
IMPROVE = ROOT / 'research' / 'improve_hips_offset'
HIGH_FABS_OUT = FTIR / 'output' / 'improve_high_fabs_comparison'
MAY_PREP_OUT = IMPROVE / 'output' / 'warren_cena_improve_prep_analysis'
FIRST_ORDER_OUT = IMPROVE / 'output' / 'improve_first_order_loading_range_analysis'
ANALOG_OUT = IMPROVE / 'output' / 'improve_addis_analog_audit'
RT_PROXY_OUT = IMPROVE / 'output' / 'improve_fed_rt_proxy_figure2'
WHITE_RT_OUT = IMPROVE / 'output' / 'white_style_rt_calibration_space'

pd.set_option('display.max_colwidth', 120)
pd.set_option('display.max_columns', 40)


def read_csv_if_exists(path: Path, **kwargs) -> pd.DataFrame:
    if path.exists():
        return pd.read_csv(path, **kwargs)
    print(f'Missing: {path.relative_to(ROOT)}')
    return pd.DataFrame()

print(ROOT)

/Users/ahmadjalil/github/aethmodular

## Existing Notebooks to Reuse

The current repo already covers most of the April 22 list. Use these as the source analyses rather than duplicating logic.

In [2]:
source_notebooks = pd.DataFrame([
    {
        'notebook': 'research/ftir_hips_chem/improve_high_fabs_comparison.ipynb',
        'role': 'Main FED pull analysis: post-2003 chemistry/fAbs cleaning, loading metrics, baseline plots, deciles, site/date context.',
        'reuse_for': 'Core IMPROVE baseline, fAbs vs EC, mass-loading comparison, high-tail tables.',
    },
    {
        'notebook': 'research/improve_hips_offset/improve_first_order_loading_range_analysis.ipynb',
        'role': 'First-order loading-range analysis with stable-period baseline and Addis/ETAD comparability screens.',
        'reuse_for': 'Axis-by-axis comparison and bounded loading/fAbs/OCEC groups.',
    },
    {
        'notebook': 'research/improve_hips_offset/warren_cena_improve_prep_analysis.ipynb',
        'role': 'Closest existing May-prep notebook: SPARTAN four-site recap, IMPROVE baseline, loading-space view, bounded fits, questions.',
        'reuse_for': 'Presentation recap for Warren/Sina/Cena.',
    },
    {
        'notebook': 'research/improve_hips_offset/improve_addis_analog_audit.ipynb',
        'role': 'Audit of Addis-like IMPROVE filters, smoke/event screens, RT optical-regime diagnostics, regression sensitivity.',
        'reuse_for': 'Paper-ready language about what IMPROVE supports and what remains untestable.',
    },
    {
        'notebook': 'research/improve_hips_offset/improve_fed_rt_proxy_figure2.ipynb',
        'role': 'FED laser R/T ratio diagnostic plots and SPARTAN raw R/T analog counts.',
        'reuse_for': 'Careful R/T visuals with caveat: not raw Warren HIPS sphere/plate signals.',
    },
    {
        'notebook': 'research/improve_hips_offset/improve_white_style_rt_calibration_space.ipynb',
        'role': 'White-style RT calibration-space audit using available FED laser fields.',
        'reuse_for': 'Calibration-space framing and top candidate/context tables.',
    },
])
source_notebooks

,notebook,role,reuse_for
0,research/ftir_hips_chem/improve_high_fabs_comparison.ipynb,"Main FED pull analysis: post-2003 chemistry/fAbs cleaning, loading metrics, baseline plots, deciles, site/date context.","Core IMPROVE baseline, fAbs vs EC, mass-loading comparison, high-tail tables."
1,research/improve_hips_offset/improve_first_order_loading_range_analysis.ipynb,First-order loading-range analysis with stable-period baseline and Addis/ETAD comparability screens.,Axis-by-axis comparison and bounded loading/fAbs/OCEC groups.
2,research/improve_hips_offset/warren_cena_improve_prep_analysis.ipynb,"Closest existing May-prep notebook: SPARTAN four-site recap, IMPROVE baseline, loading-space view, bounded fits, que...",Presentation recap for Warren/Sina/Cena.
3,research/improve_hips_offset/improve_addis_analog_audit.ipynb,"Audit of Addis-like IMPROVE filters, smoke/event screens, RT optical-regime diagnostics, regression sensitivity.",Paper-ready language about what IMPROVE supports and what remains untestable.
4,research/improve_hips_offset/improve_fed_rt_proxy_figure2.ipynb,FED laser R/T ratio diagnostic plots and SPARTAN raw R/T analog counts.,Careful R/T visuals with caveat: not raw Warren HIPS sphere/plate signals.
5,research/improve_hips_offset/improve_white_style_rt_calibration_space.ipynb,White-style RT calibration-space audit using available FED laser fields.,Calibration-space framing and top candidate/context tables.

## Task Map

Status meanings:

- **Done / reusable**: already has notebook output that can go into a recap.
- **Polish from existing outputs**: no major new analysis; make clearer tables/figures or tighten language.
- **Do as new focused analysis**: feasible with current repo data, but should be a small scoped notebook/cell block.
- **External dependency**: requires Warren/Sina/Alex or data not exposed in FED/SPARTAN files.

In [3]:
tasks = pd.DataFrame([
    {
        'workstream': 'IMPROVE data analysis',
        'task': 'Restrict analysis to post-recalibration data, using 2003-forward until Warren exact cutoff is confirmed.',
        'status': 'Done / reusable',
        'repo_evidence': 'improve_high_fabs_comparison current pull spans 2003-01-03 to 2025-07-30; first-order notebook documents the cutoff note.',
        'next_action': 'Keep 2003-forward as working cutoff; ask Warren for exact recalibration date/citation wording.',
        'priority': 'High',
    },
    {
        'workstream': 'IMPROVE data analysis',
        'task': 'Remake core FABS vs EC cross-plots on post-2003 data without arbitrary FABS thresholds.',
        'status': 'Done / reusable',
        'repo_evidence': 'improve_fabs_ec_scatter.png, improve_fabs_ec_focus_origin.png, improve_fabs_ec_fit_summary.csv, improve_post2003_baseline_before_screening.png.',
        'next_action': 'Use the baseline panels in the May recap; avoid threshold-screened plots as the opening result.',
        'priority': 'High',
    },
    {
        'workstream': 'IMPROVE data analysis',
        'task': 'Present all-data scatter as raw points and binned/density plot.',
        'status': 'Done / reusable',
        'repo_evidence': 'improve_fabs_ec_scatter.png and improve_fabs_ec_density_origin.png exist in the high-fAbs output folder.',
        'next_action': 'Choose the cleaner one-panel figure for slides and keep raw scatter in backup.',
        'priority': 'High',
    },
    {
        'workstream': 'IMPROVE data analysis',
        'task': 'Convert IMPROVE concentration to mass/loading for direct SPARTAN comparison.',
        'status': 'Done / reusable',
        'repo_evidence': 'improve_valid_cleaned.csv has volume_m3, EC_loading_ug, and EC_loading_ug_cm2_* fields where flow/duration are available.',
        'next_action': 'Use primary loading column consistently and state area assumption.',
        'priority': 'High',
    },
    {
        'workstream': 'Axis-by-axis comparison',
        'task': 'Find IMPROVE samples with EC mass loadings in the Addis/ETAD/SPARTAN range.',
        'status': 'Done / reusable',
        'repo_evidence': 'improve_first_order_comparable_rows.csv, improve_etad_axis_overlap_counts.csv, all_bounds_p05p95_rows.csv.',
        'next_action': 'Use p05-p95 Addis/ETAD bounds as the primary screen; keep min-max as sensitivity.',
        'priority': 'High',
    },
    {
        'workstream': 'Axis-by-axis comparison',
        'task': 'For high-FABS IMPROVE samples, summarize EC mass loading.',
        'status': 'Polish from existing outputs',
        'repo_evidence': 'improve_high_fabs_loading_overlap.csv, improve_top_fabs_samples.csv, improve_top_fabs_candidates.csv.',
        'next_action': 'Make a compact top-candidate table with site, date, fAbs, ECf, EC loading, OC/EC, FE/EC, RT availability.',
        'priority': 'High',
    },
    {
        'workstream': 'Axis-by-axis comparison',
        'task': 'Decide whether IMPROVE and Addis are measuring comparable regimes in the high range and what that implies for MAC.',
        'status': 'Polish from existing outputs',
        'repo_evidence': 'bounded_group_fabs_ec_fit_summary.csv, improve_bounded_group_fits.csv, improve_analog_fit_summary.csv.',
        'next_action': 'Frame as evidence for rare/optically distinct high-loading regime, not a final MAC correction proof.',
        'priority': 'High',
    },
    {
        'workstream': 'Filter lots',
        'task': 'Confirm which MTL filter lots Addis Ababa samples came from.',
        'status': 'External dependency',
        'repo_evidence': 'SPARTAN raw R/T lot counts exist for available fields, but authoritative Addis lot provenance still needs Alex/operations confirmation.',
        'next_action': 'Ask Alex or SPARTAN operations for Addis MTL lot IDs and date ranges.',
        'priority': 'Low',
    },
    {
        'workstream': 'Filter lots',
        'task': 'Assess how much lot issue constrains IMPROVE R/T overlay on Warren plot.',
        'status': 'External dependency',
        'repo_evidence': 'FED does not expose filter lot ID or raw Warren Figure 2 HIPS R/T signals; repo can only provide diagnostic FED laser R/T plots.',
        'next_action': 'Ask Warren whether lot differences matter for comparing IMPROVE and SPARTAN on R/T plots; keep Ann note as lower priority.',
        'priority': 'Low',
    },
    {
        'workstream': 'Presentation prep',
        'task': 'Build full paper-style recap across Beijing, Delhi, JPL, Addis plus IMPROVE.',
        'status': 'Do as new focused analysis',
        'repo_evidence': 'warren_cena_improve_prep_analysis already has most components; SPARTAN four-site figures and fits are exported.',
        'next_action': 'Turn existing figures/tables into a recap notebook or deck with datasets, cross-plots, similarities/differences, and expert questions.',
        'priority': 'High',
    },
    {
        'workstream': 'Questions for Warren',
        'task': 'Prepare questions on HIPS measurement limits, correction options, lot effects, and pixelation vs mass-loading effects.',
        'status': 'Polish from existing outputs',
        'repo_evidence': 'warren_cena_improve_prep_analysis has a questions section; FED missing-data caveat is documented.',
        'next_action': 'Add one figure/table next to each question so the meeting stays concrete.',
        'priority': 'High',
    },
    {
        'workstream': 'Questions for Sina',
        'task': 'Prepare questions on Addis flow-rate fix, newer data, and high-loading aethalometer behavior.',
        'status': 'External dependency',
        'repo_evidence': 'Flow-fix analyses exist for SPARTAN sites, but deployment status/newer Addis aeth data are not discoverable from current repo outputs.',
        'next_action': 'Ask Sina directly; if newer data arrive, rerun standard match/exclusion/plot workflow.',
        'priority': 'High',
    },
])

tasks

,workstream,task,status,repo_evidence,next_action,priority
0,IMPROVE data analysis,"Restrict analysis to post-recalibration data, using 2003-forward until Warren exact cutoff is confirmed.",Done / reusable,improve_high_fabs_comparison current pull spans 2003-01-03 to 2025-07-30; first-order notebook documents the cutoff ...,Keep 2003-forward as working cutoff; ask Warren for exact recalibration date/citation wording.,High
1,IMPROVE data analysis,Remake core FABS vs EC cross-plots on post-2003 data without arbitrary FABS thresholds.,Done / reusable,"improve_fabs_ec_scatter.png, improve_fabs_ec_focus_origin.png, improve_fabs_ec_fit_summary.csv, improve_post2003_bas...",Use the baseline panels in the May recap; avoid threshold-screened plots as the opening result.,High
2,IMPROVE data analysis,Present all-data scatter as raw points and binned/density plot.,Done / reusable,improve_fabs_ec_scatter.png and improve_fabs_ec_density_origin.png exist in the high-fAbs output folder.,Choose the cleaner one-panel figure for slides and keep raw scatter in backup.,High
3,IMPROVE data analysis,Convert IMPROVE concentration to mass/loading for direct SPARTAN comparison.,Done / reusable,"improve_valid_cleaned.csv has volume_m3, EC_loading_ug, and EC_loading_ug_cm2_* fields where flow/duration are avail...",Use primary loading column consistently and state area assumption.,High
4,Axis-by-axis comparison,Find IMPROVE samples with EC mass loadings in the Addis/ETAD/SPARTAN range.,Done / reusable,"improve_first_order_comparable_rows.csv, improve_etad_axis_overlap_counts.csv, all_bounds_p05p95_rows.csv.",Use p05-p95 Addis/ETAD bounds as the primary screen; keep min-max as sensitivity.,High
5,Axis-by-axis comparison,"For high-FABS IMPROVE samples, summarize EC mass loading.",Polish from existing outputs,"improve_high_fabs_loading_overlap.csv, improve_top_fabs_samples.csv, improve_top_fabs_candidates.csv.","Make a compact top-candidate table with site, date, fAbs, ECf, EC loading, OC/EC, FE/EC, RT availability.",High
6,Axis-by-axis comparison,Decide whether IMPROVE and Addis are measuring comparable regimes in the high range and what that implies for MAC.,Polish from existing outputs,"bounded_group_fabs_ec_fit_summary.csv, improve_bounded_group_fits.csv, improve_analog_fit_summary.csv.","Frame as evidence for rare/optically distinct high-loading regime, not a final MAC correction proof.",High
7,Filter lots,Confirm which MTL filter lots Addis Ababa samples came from.,External dependency,"SPARTAN raw R/T lot counts exist for available fields, but authoritative Addis lot provenance still needs Alex/opera...",Ask Alex or SPARTAN operations for Addis MTL lot IDs and date ranges.,Low
8,Filter lots,Assess how much lot issue constrains IMPROVE R/T overlay on Warren plot.,External dependency,FED does not expose filter lot ID or raw Warren Figure 2 HIPS R/T signals; repo can only provide diagnostic FED lase...,Ask Warren whether lot differences matter for comparing IMPROVE and SPARTAN on R/T plots; keep Ann note as lower pri...,Low
9,Presentation prep,"Build full paper-style recap across Beijing, Delhi, JPL, Addis plus IMPROVE.",Do as new focused analysis,warren_cena_improve_prep_analysis already has most components; SPARTAN four-site figures and fits are exported.,"Turn existing figures/tables into a recap notebook or deck with datasets, cross-plots, similarities/differences, and...",High
10,Questions for Warren,"Prepare questions on HIPS measurement limits, correction options, lot effects, and pixelation vs mass-loading effects.",Polish from existing outputs,warren_cena_improve_prep_analysis has a questions section; FED missing-data caveat is documented.,Add one figure/table next to each question so the meeting stays concrete.,High
11,Questions for Sina,"Prepare questions on Addis flow-rate fix, newer data, and high-loading aethalometer behavior.",External dependency,"Flow-fix analyses exist for SPARTAN sites, but deployment status/newer Addis aeth data are not discoverable from cur...","Ask Sina directly; if newer data arrive, rerun standard match/exclusion/plot workflow.",High

## Current Evidence Snapshot

These cells load the existing exported summaries so the notebook can be rerun as a compact status check before a meeting.

In [4]:
current_pull = read_csv_if_exists(HIGH_FABS_OUT / 'current_pull_interpretation.csv')
current_pull.T

                                                                                                                                                        0
valid_rows                                                                                                                                         379697
date_min                                                                                                                                       2003-01-03
date_max                                                                                                                                       2025-07-30
etad_like_rows                                                                                                                                        207
high_tail_rows                                                                                                                                          5
above_etad_max_rows                                                                                                                                     3
rt_joined_rows                                                                                                                                     147380
loading_available_rows                                                                                                                             152029
etad_like_loading_available_rows                                                                                                                       77
conclusion                        The full local FED pull finds real IMPROVE samples in the ETAD fAbs range, but the strict high-tail group is still t...

In [5]:
spartan_loading = read_csv_if_exists(HIGH_FABS_OUT / 'spartan_site_loading_summary.csv')
cols = [
    'Site', 'paired_n', 'HIPS_Fabs_median', 'HIPS_Fabs_max', 'EC_ftir_median',
    'EC_loading_ug_median', 'EC_loading_ug_cm2_p05', 'EC_loading_ug_cm2_median', 'EC_loading_ug_cm2_p95',
]
spartan_loading[[c for c in cols if c in spartan_loading.columns]]

,Site,paired_n,HIPS_Fabs_median,HIPS_Fabs_max,EC_ftir_median,EC_loading_ug_median,EC_loading_ug_cm2_p05,EC_loading_ug_cm2_median,EC_loading_ug_cm2_p95
0,CHTS,163,12.865126,37.917433,1.221340,8.473220,0.646819,2.400346,6.705304
1,ETAD,190,47.132129,85.852735,4.624584,33.503921,4.725187,9.491196,19.640041
2,INDH,63,38.920651,225.518313,3.275819,16.300221,0.768685,4.617626,14.328792
3,USPA,130,4.702318,10.394390,0.487629,3.519160,0.509988,0.996929,1.681416

In [6]:
fit_summary = read_csv_if_exists(HIGH_FABS_OUT / 'improve_fabs_ec_fit_summary.csv')
keep_groups = ['all_valid', 'post_2017_all_valid', 'ETAD_like', 'high_tail']
fit_cols = ['group', 'n', 'slope', 'intercept', 'r2', 'origin_mac', 'within_site_slope']
fit_summary.loc[fit_summary['group'].isin(keep_groups), [c for c in fit_cols if c in fit_summary.columns]]

,group,n,slope,intercept,r2,origin_mac,within_site_slope
0,all_valid,379697,5.367442,1.141782,0.567268,6.704092,4.182955
1,post_2017_all_valid,131644,3.436665,1.309302,0.390853,4.428801,2.822595
2,ETAD_like,207,0.143459,34.441397,0.008218,3.600209,0.404174

In [7]:
overlap = read_csv_if_exists(HIGH_FABS_OUT / 'improve_high_fabs_loading_overlap.csv')
if not overlap.empty:
    display(overlap.head(15))

,fAbs_group,loading_group,n_overlap,sites,fAbs_median,EC_median,EC_loading_ug_cm2_primary_median
0,ETAD_like,loading_ETAD_ge_median_area_2p2,77,29,34.460,3.049250,22.482434
1,ETAD_like,loading_ETAD_ge_median_area_3p5,74,26,34.730,3.082305,23.018838
2,ETAD_like,loading_ETAD_ge_median_area_3p53,74,26,34.730,3.082305,23.018838
3,ETAD_like,loading_ETAD_ge_median_area_4p0,73,25,34.460,3.086240,23.111623
4,ETAD_like,loading_ETAD_p05p95_area_4p0,37,16,35.600,2.182270,17.878450
5,ETAD_like,loading_ETAD_p05p95_area_3p5,25,14,33.130,2.066320,16.394987
6,ETAD_like,loading_ETAD_p05p95_area_3p53,25,14,33.130,2.066320,16.394987
7,ETAD_like,EC_mass_ETAD_p05p95,25,14,33.130,2.066320,16.394987
8,ETAD_like,loading_ETAD_IQR_area_3p5,9,8,31.110,1.619680,11.536120
9,ETAD_like,loading_ETAD_IQR_area_4p0,9,7,30.980,1.676490,12.415253
10,ETAD_like,loading_ETAD_IQR_area_3p53,8,7,31.045,1.648085,11.697650
11,ETAD_like,EC_mass_ETAD_IQR,8,7,31.045,1.648085,11.697650
12,ETAD_like,loading_ETAD_p05p95_area_2p2,6,6,33.705,1.648085,9.409275
13,ETAD_like,loading_ETAD_IQR_area_2p2,2,2,33.205,1.218840,7.253600
14,fabs_ge50,loading_ETAD_ge_median_area_2p2,12,7,65.515,4.708810,29.988165

In [8]:
axis_overlap = read_csv_if_exists(MAY_PREP_OUT / 'improve_etad_axis_overlap_counts.csv')
if axis_overlap.empty:
    axis_overlap = read_csv_if_exists(FIRST_ORDER_OUT / 'screening_group_counts.csv')
axis_overlap

,screen,n,sites,first_year,last_year,pct_valid_loading
0,"valid loading, post-2003",152029,177,2015,2025,100.000000
1,ETAD fAbs p05-p95 only,36,15,2015,2025,0.023680
2,ETAD EC concentration p05-p95 only,399,78,2015,2025,0.262450
3,ETAD EC mass p05-p95 only,7196,166,2015,2025,4.733307
4,ETAD EC surface p05-p95 only,7299,166,2015,2025,4.801058
5,fAbs + EC mass + EC surface,10,7,2016,2025,0.006578
6,fAbs + EC conc + EC mass + EC surface,2,2,2023,2023,0.001316

In [9]:
rt_availability = read_csv_if_exists(RT_PROXY_OUT / 'improve_fed_rt_proxy_availability.csv')
rt_pair_summary = read_csv_if_exists(RT_PROXY_OUT / 'improve_fed_rt_proxy_pair_summary.csv')
print('RT availability')
display(rt_availability.head(20))
print('RT pair summary')
display(rt_pair_summary.head(20))

RT availability

                         group       n
0             all cleaned rows  379697
1                    post-2003  379697
2  post-2003 rt_available flag  147380
3    post-2003 initial RT pair  147380
4      post-2003 final RT pair  147380
5    post-2003 minimum RT pair  147380

RT pair summary

,pair,n,sites,year_min,year_max,etad_comparable_n,high_fabs_ge70_n,RefI_635_Val_median,TransI_635_Val_median,RefF_635_Val_median,TransF_635_Val_median,RefM_635_Val_median,TransM_635_Val_median
0,initial,147380,167,2016,2025,10,5,353.12,165.39,NaN,NaN,NaN,NaN
1,final,147380,167,2016,2025,10,5,NaN,NaN,397.4,216.86,NaN,NaN
2,minimum,147380,167,2016,2025,10,5,NaN,NaN,NaN,NaN,297.24,70.59

## Recommended New Work

The best next notebook/deck is **not** a new exploratory IMPROVE data pull. The repo already has that. The useful new artifact is a polished May meeting recap that stitches together:

1. SPARTAN four-site HIPS/FTIR/aethalometer behavior.
2. IMPROVE post-2003 baseline without arbitrary fAbs thresholds.
3. Loading-space overlap between IMPROVE and Addis/ETAD.
4. High-fAbs candidate table and regression sensitivity.
5. FED laser R/T diagnostic caveat.
6. Explicit Warren/Sina question slides.

Suggested source notebook to promote: `research/improve_hips_offset/warren_cena_improve_prep_analysis.ipynb`.

Suggested generated artifact: a short paper-style recap notebook or slide deck, using the existing exported CSV/PNG files rather than recomputing everything from scratch.

In [10]:
recommended_next_steps = pd.DataFrame([
    {
        'step': 1,
        'action': 'Rename/relabel any remaining "HIPS R/T proxy" language to "FED laser R/T ratio fields" unless raw SPARTAN HIPS R/T is being shown.',
        'why': 'Avoids overclaiming that FED reproduces Warren Figure 2.',
    },
    {
        'step': 2,
        'action': 'Build one high-fAbs candidate table from improve_top_fabs_samples, high-fAbs loading overlap, and RT availability.',
        'why': 'Directly answers Ann/Warren: what EC loading do high-fAbs IMPROVE samples actually have?',
    },
    {
        'step': 3,
        'action': 'Create a May recap deck/notebook from warren_cena_improve_prep_analysis outputs.',
        'why': 'This is the highest-value deliverable before separate expert meetings.',
    },
    {
        'step': 4,
        'action': 'Send external questions: Warren for recalibration cutoff/raw HIPS/lot/pixelation; Sina for Addis flow fix/new aeth data/high-loading behavior; Alex/ops for MTL lot IDs.',
        'why': 'These cannot be resolved from the current repo or FED parameter pull.',
    },
])
recommended_next_steps

,step,action,why
0,1,"Rename/relabel any remaining ""HIPS R/T proxy"" language to ""FED laser R/T ratio fields"" unless raw SPARTAN HIPS R/T i...",Avoids overclaiming that FED reproduces Warren Figure 2.
1,2,"Build one high-fAbs candidate table from improve_top_fabs_samples, high-fAbs loading overlap, and RT availability.",Directly answers Ann/Warren: what EC loading do high-fAbs IMPROVE samples actually have?
2,3,Create a May recap deck/notebook from warren_cena_improve_prep_analysis outputs.,This is the highest-value deliverable before separate expert meetings.
3,4,Send external questions: Warren for recalibration cutoff/raw HIPS/lot/pixelation; Sina for Addis flow fix/new aeth d...,These cannot be resolved from the current repo or FED parameter pull.

## Meeting Question Draft

### Warren

- Are the Addis/SPARTAN filters in a regime where HIPS is being asked to measure beyond its reliable calibration space?
- Is there a defensible correction analogous to the 2025 IMPROVE correction, or would that require raw HIPS sphere/plate signals and blank-line metadata that FED does not expose?
- Does the MTL filter-lot difference matter enough to affect an IMPROVE/SPARTAN R/T overlay, or is it lower order than loading/optical-regime effects?
- Is the PTFE pixelation effect meaningful at these high loadings, or second order relative to mass loading and optical saturation?
- What exact post-recalibration cutoff date should be used for a post-2003 IMPROVE analysis?

### Sina / SPARTAN Operations

- Was the aethalometer flow-rate fix deployed at the Addis Ababa site, and on what date?
- Is there newer Addis aethalometer data with corrected flow rates that can be matched against the filter record?
- Are there known aethalometer issues at high mass loadings that could parallel the HIPS behavior?
- Which MTL lot IDs and lot date ranges apply to the Addis Ababa filters?